<?php

namespace Tool\Bundle\EntityFileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityFileRepository extends EntityRepository
{
}
